name: Path_Finder-EKS CI/CD

on:
  push:
    branches: 
      - main
  #   paths-ignore:
  #     - 'README.md'
  #     - '.github/**'

  # workflow_dispatch:
     

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: development/path-finder       
  OPENAI_API : ${{ secrets.OPENAI_API }}
  GEO_API : ${{ secrets.GEO_API }}
  DATABASE_URI : ${{ secrets.DATABASE_URI }}
                                               
jobs:
  Build_And_Push:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Check out code and pull
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: 20

    - name: install dependencies and Build the application
      working-directory: ./app
      run: |
         npm install
         echo "starting http server"
         node index.js & 
         echo $! > app.pid

    - name: wait for server to be upload
      run: sleep 5


    - name: Run tests
      run: |
         echo "testing app"
         curl -f http://localhost:3000
         sleep 5

    - name: Stop application
      run: |
        echo "Stopping app..."
        kill $(cat app.pid) || true


    - name: Build Docker image
      run: |
         echo "building app image"
         docker build -t my-app:latest .


    - name: Deploy testing environment
      run: |
          echo "testing enviroment up"
          docker compose up -d  
      
    - name: Check running containers and existed images
      run: |
         docker ps -a
         docker images
        
    - name: wait application to be upload
      run: |
         sleep 5
          
    - name: Run tests
      run: |
         echo "app container testing"
         curl http://localhost:80

    - name: Remove testing environment
      if: always()
      run: |
         echo "testing enviroment down"
         docker compose down -v

        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
         aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: tag, and push image to Amazon ECR
      id: build-image #need to check it
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: | 
         docker tag my-app:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
        

    - name: Update GitOps repository
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
          echo "Cloning GitOps repository..."
          git clone \
            https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/tamer98/SmartPath-AI_GitOps.git \
            gitops
            
          echo "Moving to Helm chart..."
          cd gitops/path-finder-ai

          echo "Current values.yaml:"
          cat values.yaml

          echo "Updating image tag..."
          sed -i "s/^  tag:.*/  tag: ${IMAGE_TAG}/" values.yaml

          echo "Updated values.yaml:"
          cat values.yaml

          echo "Configuring Git..."
          git config user.name "SmartPath AI CI/CD"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "Committing GitOps change..."
          git add values.yaml
          git commit \
            -m "Update path-finder-ai image to ${IMAGE_TAG}"

          echo "Pushing GitOps change..."
          git push
